[package]
name = "afptool-rs"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "afptool_rs"
path = "src/lib.rs"

[[bin]]
name = "afptool-rs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"
md5 = "0.8"

[dev-dependencies]
tempfile = "3.8.0"
assert_cmd = "2.0.12"
predicates = "3.0.3"